spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    host: localhost
    port: 13500
    database: book-rental
    username: root
    password: mongodb
    authentication-database: admin

server:
  port: 8001

